name: Build APK

on:
  workflow_dispatch:
jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Flutter
        uses: subosito/flutter-action@v2.16.0
        with:
          flutter-version: '3.19.6'
          channel: 'stable'
          cache: true
      - name: Get dependencies
        run: flutter pub get
      - name: Analyze
        run: flutter analyze
      - name: Run tests
        run: flutter test
      - name: Build APK
        run: flutter build apk
      - name: Upload generated apk to slack
        uses: MeilCli/slack-upload-file@v4
        id: message
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
          file_path: 'build/app/outputs/apk/release/app-release.apk'
          file_name: 'app-release.apk'
          file_type: 'apk'
          initial_comment: '${{ github.ref }} - deployed the apk file to slack'
