name: Unit Test

on:
  push:
    branches: [ github_actions, master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - uses: futureware-tech/simulator-action@v3
      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2.16.0
        with:
          flutter-version: '3.19.6'
      - name: Restore packages
        run: flutter pub get
      - name: Analyze
        run: flutter analyze
      - name: Run tests
        run: flutter test --coverage
      - name: Upload coverage to codecov
        run: curl -s https://codecov.io/bash
        shell: bash